request:
  url: "https://www.104.com.tw/jobs/search/api/jobs"
  area_codes_path: "104_area_codes.json"
  start_page: 1
  params:
    area_names:
      - "台北市"
      - "新北市中和區"
      - "新北市永和區"
      - "新北市新店區"
      - "新北市板橋區"
    jobsource: "joblist_search"
    keyword: "資料工程師 數據工程師 Data Engineer"
    mode: "s"
    order: "15"
    ro: "1"
    pagesize: "20"
    s9: "1"
    searchJobs: "1"

max_pages: 3
timeout: 30
output_csv: "104_jobs.csv"
